---
version: ~> 1.0

os: linux
dist: bionic    # Needed for Python 3.6 or later required by Molecule.
language: shell

env:
  - docker_repo=geerlingguy/docker-debian10-ansible
  - docker_repo=geerlingguy/docker-ubuntu2004-ansible
  - docker_repo=geerlingguy/docker-ubuntu1804-ansible
  - docker_repo=resin/rpi-raspbian

jobs:
  # TODO: Fix these failures?
  allow_failures:
    # TODO: Fixing the Raspbian build is going to require QEMU and
    #       binfmt_misc support. See:
    #       https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/
    #       In the mean time, allow this to fail.
    - env: docker_repo=resin/rpi-raspbian

before_install:
    # Upgrade to newest Docker Engine.
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
    - sudo apt-get install python3-pip python3-setuptools python3-wheel
    - python3 -m pip install --user --upgrade pip
    - python3 -m pip install --user ansible molecule[docker] yamllint ansible-lint

script:
    - molecule test
