---
language: minimal

env:
  - docker_repo: resin/rpi-raspbian
  - docker_repo: geerlingguy/docker-debian9-ansible
  - docker_repo: geerlingguy/docker-ubuntu1804-ansible
  # TODO: Support for RedHat-based systems.
  #- docker_repo: geerlingguy/docker-centos7-ansible
  #- docker_repo: geerlingguy/docker-fedora27-ansible

matrix:
  # TODO: Fix these failures?
  allow_failures:
    # TODO: Fixing the Raspbian build is going to require QEMU and
    #       binfmt_misc support. See:
    #       https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/
    #       In the mean time, allow this to fail.
    - env: docker_repo=resin/rpi-raspbian

install:
  - docker image pull ${docker_repo}
  - container_id=$(mktemp)
  - >
    docker container run --detach --privileged
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume ${PWD}:/etc/ansible/roles/ansible-role-tor:ro
    ${docker_repo}:latest > ${container_id}

  # Bootstrap to ensure Ansible is available in the container.
  # This is to ensure that the containers not already pre-imaged with
  # Ansible installed (i.e., Raspbian image) will have it available.
  - >
    docker container exec --tty $(cat ${container_id}) env TERM=xterm
    pip install ansible

script:
  # Check Ansible role/playbook syntax.
  - >
    docker container exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook --syntax-check /etc/ansible/roles/ansible-role-tor/tests/test.yml

  # Ensure the role/playbook runs without errors or failures.
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/ansible/roles/ansible-role-tor/tests/test.yml

  # Run the role/playbook again to test idempotence.
  - idempotence=$(mktemp)
  - >
    docker exec "$(cat ${container_id})"
    ansible-playbook /etc/ansible/roles/ansible-role-tor/tests/test.yml
    | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    curl --silent --proxy socks5://127.0.0.1:9050 https://check.torproject.org/api/ip
    | grep -q 'IsTor":true'

after_script:
  - docker container rm -f "$(cat ${container_id})"
