---
- name: Cleanup
  hosts: all
  gather_facts: false
  vars_files:
    - vars/main.yaml

  tasks:
    - name: Cleanup temporary directory.
      local_action:
          module: file
          path: "tmp/"
          state: absent
