---
dependency:
  name: galaxy
#lint: |
#  set -e
#  yamllint .
#  ansible-lint
driver:
  name: docker
platforms:
  - name: instance
    image: ${docker_repo:-geerlingguy/docker-ubuntu1804-ansible:latest}
    pre_build_image: true
    volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: ${docker_command:-""}
provisioner:
  name: ansible
verifier:
  name: ansible
