---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update APT cache (Debian).
      when: ansible_os_family == 'Debian'
      apt:
        update_cache: true

    - name: Install tools for role verification.
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl  # To test Tor client connections.
        - nginx # To run a test HTTP Onion service.

    - name: Start Web server.
      service:
        name: nginx
        state: started
