---
- name: Verify
  hosts: all
  tasks:
    - name: Access clearnet check.torproject.org via Tor.
      command: >
          curl --proxy socks5h://127.0.0.1:9050
          https://check.torproject.org/api/ip
      args:
        warn: false
      register: cmd

    - name: Assert connection to check.torproject.org is via Tor.
      assert:
        that: cmd.stdout.startswith('{"IsTor":true')

    - name: Pause to let self-hosted Onion sites come online.
      pause:
        minutes: 2

    - name: Attempt connection to self-hosted v3 Onion site.
      shell: >
          curl --proxy socks5h://127.0.0.1:9050
          http://$(sudo cat /var/lib/tor/onion-services/onion-v3-test/hostname)/
      args:
        warn: false

    - name: Attempt connection to self-hosted v2 Onion site.
      shell: >
          curl --proxy socks5h://127.0.0.1:9050
          http://$(sudo cat /var/lib/tor/onion-services/onion-v2-test/hostname)/
      args:
        warn: false
