---
- name: Verify
  hosts: all
  tasks:
    - name: Attempt basic Tor client connection.
      command: >
          curl --proxy socks5h://127.0.0.1:9050
          https://check.torproject.org/api/ip
      args:
        warn: false
      register: cmd

    - name: Assert basic Tor client connections succeed.
      assert:
        that: cmd.stdout.startswith('{"IsTor":true')

    - name: Attempt connection to self-hosted v3 Onion site.
      shell: >
          curl --proxy socks5h://127.0.0.1:9050
          http://$(sudo cat /var/lib/tor/onion-services/onion-v3-test/hostname)/
      register: cmd

    - name: Assert v3 Onion service is online.
      assert:
        that: "'Welcome to nginx' in cmd.stdout"

    - name: Attempt connection to self-hosted authenticated v3 Onion site.
      shell: >
          curl --proxy socks5h://127.0.0.1:9050
          http://$(sudo cat /var/lib/tor/onion-services/authenticated-onion-v3-test/hostname)/
      register: cmd

    - name: Assert v3 Onion service is online.
      assert:
        that: "'Welcome to nginx' in cmd.stdout"

    - name: Wait for self-hosted v2 Onion site to come online.
      pause:
        minutes: 3

    - name: Attempt connection to self-hosted v2 Onion site.
      shell: >
          curl --proxy socks5h://127.0.0.1:9050
          http://$(sudo cat /var/lib/tor/onion-services/onion-v2-test/hostname)/
      register: cmd

    - name: Assert v2 Onion service is online.
      assert:
        that: "'Welcome to nginx' in cmd.stdout"

    - name: Attempt connection to self-hosted authenticated v2 Onion site.
      shell: >
          curl --proxy socks5h://127.0.0.1:9050
          http://$(sudo cat /var/lib/tor/onion-services/authenticated-onion-v2-test/hostname)/
      register: cmd

    - name: Assert v2 Onion service is online.
      assert:
        that: "'Welcome to nginx' in cmd.stdout"
