---
- name: Prepare
  hosts: all
  tasks:
    - name: Provision instance as root.
      become: true
      block:
        - name: Update APT cache (Debian).
          when: ansible_os_family == 'Debian'
          become: true
          apt:
            update_cache: true

        - name: Install tools for role verification.
          become: true
          package:
            name: "{{ item }}"
            state: present
          loop:
            - curl  # To test Tor client connections.
            - nginx # To run a test HTTP Onion service.

        - name: Start Web server.
          service:
            name: nginx
            state: started

    - name: Generate tester v3 Onion credentials.
      local_action:
        module: command
        cmd: "./scripts/tor-auth-x25519-gen.py"
      register: cmd

    - name: Set facts for tester v3 Onion credentials.
      set_fact:
        tester_privkey: "{{ cmd.stdout_lines[0].split(': ') | last }}"
        tester_pubkey: "{{ cmd.stdout_lines[1].split(': ') | last }}"

    - name: Discover authenticated v3 Onion service hostname.
      command: >
          cat /var/lib/tor/onion-services/authenticated-onion-v3-test/hostname
      register: cmd_v3
      changed_when: false

    - name: Discover authenticated v2 Onion service hostname.
      command: >
          cat /var/lib/tor/onion-services/authenticated-onion-v2-test/hostname
      register: cmd_v2
      changed_when: false
