---
- name: Verify
  hosts: all
  tasks:
    - name: Attempt connection to self-hosted authenticated v3 Onion site.
      shell: >
          curl --proxy socks5h://127.0.0.1:9050
          http://$(sudo cat /var/lib/tor/onion-services/authenticated-onion-v3-test/hostname)/
      args:
        warn: false
      register: cmd

    - name: Assert authenticated v3 Onion service is online and reachable.
      assert:
        that: "'Welcome to nginx' in cmd.stdout"

    - name: Wait for self-hosted v2 Onion site to come online.
      pause:
        minutes: 3

    - name: Attempt connection to self-hosted authenticated v2 Onion site.
      shell: >
          curl --proxy socks5h://127.0.0.1:9050
          http://$(sudo cut -f 1 -d ' ' /var/lib/tor/onion-services/authenticated-onion-v2-test/hostname)/
      args:
        warn: false
      register: cmd

    - name: Assert authenticated v2 Onion service is online and reachable.
      assert:
        that: "'Welcome to nginx' in cmd.stdout"
